#!/usr/bin/python3
from  sys import argv
import time

def factorise(a):
    for j in range(2, int(a ** 0.5) + 1):
            if a % j == 0:
                return (a//j, j)
            j += 1
    return None

if __name__ == "__main__":
    if len(argv) != 2:
        print("Usage: factors <file>")
        exit(1)
    a = argv[1]
    try:
        file = open(a, 'r')
        content = file.read()
        lines = content.split('\n')
        file.close()
    except FileNotFoundError:
        print("file not found")
        exit(1)
    start_time = time.time()
    for line in lines:
        if line.strip():
            a = int(line)
            b = factorise(a)
            if b:
                print("{}={}*{}".format(a, b[0], b[1]))
        if time.time() - start_time > 5:
            print("exceded time limit")
            exit(1)

