#!/usr/bin/python3
from  sys import argv
a = argv[1]
file = open(a, 'r')
content = file.read()
lines = content.split('\n')
file.close()

for line in lines:
    if line.strip():
        a = int(line)
        b = a // 2
        for j in range(2, b):
            if a % j == 0:
                print("{}={}*{}".format(a, a//j, j))
                break
