#!/usr/bin/python3
from  sys import argv

def is_prime(number):
    if number < 2:
        return False
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            return False
    return True

a = argv[1]
file = open(a, 'r')
content = file.read()
lines = content.split('\n')
file.close()

for line in lines:
    if line.strip():
        a = int(line)
        b = a // 2
        for j in range(2, b + 1):
            if a % j == 0:
                if is_prime(j) and is_prime(a//j):
                    print("{}={}*{}".format(a, a//j, j))
                    break
                else:
                    continue
