#!/usr/bin/python3
from  sys import argv

def is_prime(number):
    if number < 2:
        return False
    if number < 4:
        return True
    if number % 2 == 0 or number % 3 == 0:
        return False
    i = 5
    while i * i <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6
    return True

a = argv[1]
file = open(a, 'r')
content = file.read()
lines = content.split('\n')
file.close()

for line in lines:
    if line.strip():
        a = int(line)
        b = int(a ** 0.5) + 1
        for j in range(2, b):
            if a % j == 0:
                if is_prime(j) and is_prime(a//j):
                    print("{}={}*{}".format(a, a//j, j))
                    break
                else:
                    continue
